# Generated by Django 3.1.2 on 2021-03-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210322_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('C', 'Country'), ('T', 'Thematic')], default='C', max_length=2),
        ),
    ]
