# Generated by Django 3.1.2 on 2021-03-22 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_section_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headlines', to='news.category'),
        ),
    ]
